In [2]:
# numpy
import numpy as np

# array? : 머신러닝 알고리즘에서 요구하는 입출력 데이터 형태
array1 = np.array([1,2,3])
print(type(array1))
print(array1.shape)

array2 = np.array([[1,2,3],[4,5,6]])
print(array2.shape)

array3 = np.array([[1,2,3]])
print(array3.shape)

# array 1과 array3 는 형태는 비슷하지만 각각 1차원과 2차원이라는 차이가 있음, array1은 단순히 숫자가 들어간 배열일뿐, 원소 위치를 찾을때 숫자 1개면되지만
# array3은 행렬이기때문에 인덱스가 2개필요함

print(array1.ndim,array3.ndim,array2.ndim)

<class 'numpy.ndarray'>
(3,)
(2, 3)
(1, 3)
1 2 2


In [19]:
# list를 쉽게 array로 바꿀수있음 
list1=[1,2,3]
print(type(list1))
array1=np.array(list1)
print(array1,array1.dtype)

# ndarray내의 데이터 타입은 연산의 특성상 같은 데이터 타입만 가능한대, 만약에 다른게 섞여있으면 크기가 더큰 데이터 타입으로 형변환을 일괄적용

list2=[1,2,'test']
array2=np.array(list2)
print(array2,array2.dtype)  # < 1,2과 문자타입으러

list3=[1,2,3.0]
array3=np.array(list3)
print(array3,array3.dtype) #<1,2가 float으로

<class 'list'>
[1 2 3] int32
['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [25]:
# 메모리줄이기  astype으로 더 작은 데이터 타입으로 바꿔 계산하는게 좋음, 메모리 문제 때문에

array_int=np.array([1,2,3])
array_float=array_int.astype('float64')
print(array_float,array_float.dtype)


array_int1=array_float.astype('int32')
print(array_int1,array_int1.dtype)

array_float=np.array([1.2,2.3,3.3])
array_int2=array_float.astype('int32')
print(array_int2,array_int2.dtype)
print(array_float.shape)
print(array_int2.shape)


[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32
(3,)
(3,)


In [32]:
# ndarray 편리하게 생성하기  arange/zeros/ones
# test데이터를 만들거나,대규모 데이터를 일괄적으로 초기화해야할때 사용함


#arrange : range에해당하는 범위를 array로 만드는거 , (start,end,몇씩차이나게할건지?)
sequence_array=np.arange(10)
print(sequence_array,sequence_array.shape)

#zeros(): 튜플 형태의 shape값을 입력하면 모둔 값을 0으로 채운 shape를 가진 array를 반환
zero_array=np.zeros((3,2),dtype='int32')
print(zero_array,zero_array.dtype)

#ones(): zeros와 동일 얘는 1로 채움
one_array=np.ones((3,2),dtype='int32') # dtype입력안하면 int64로채움
print(one_array,one_array.dtype)

[0 1 2 3 4 5 6 7 8 9] (10,)
[[0 0]
 [0 0]
 [0 0]] int32
[[1 1]
 [1 1]
 [1 1]] int32


In [4]:
# ndarray의 차원과 크기를 변경하는 reshape()

array=np.arange(10)
print(array,array.shape)

array2=array.reshape(1,10)
print(array2,array2.shape)

array3=array.reshape(2,5)
print(array3,array3.shape)

# reshape에 -1을 사용하면 ndarray에 호환되는 shape로 자동변환해줌 
array4=array.reshape(5,-1)
print(array4,array.shape)

#자주 쓰는 형태 reshape(-1,1) 무조건 2차원으로 차원수를 바꿔버림
array5=array.reshape(1,-1)
print(array5,array5.shape)

array1=np.arange(8)
array3d=array1.reshape(2,2,2) # depth,행,렬 > 행렬 묶음이 2개 
print(array3d.tolist())

# 3차원 ndarray를 2차원으로
array5=array3d.reshape(-1,1)
print(array5.tolist(),array5.shape)

# 1차원을 2차원으로
array6 =array1.reshape(-1,1)
print(array6.tolist(),array6.shape)

[0 1 2 3 4 5 6 7 8 9] (10,)
[[0 1 2 3 4 5 6 7 8 9]] (1, 10)
[[0 1 2 3 4]
 [5 6 7 8 9]] (2, 5)
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] (10,)
[[0 1 2 3 4 5 6 7 8 9]] (1, 10)
[[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
[[0], [1], [2], [3], [4], [5], [6], [7]] (8, 1)
[[0], [1], [2], [3], [4], [5], [6], [7]] (8, 1)


In [7]:
# numpy -indexing

#1.특정 데이터만 추출하기
array1= np.arange(1,10)
print(array1,array1[2],array[-1],array[-2])
array1[2]=15
print(array1)

array1d=np.arange(1,10)
array2d=array1d.reshape(3,3)

print(array2d)
print(array2d[0,0],array2d[2,2],array2d[1,2])
# axis=0은 -> 행방향, axis=1은 열방향 3차원의 경우 axis=2는 높이방향

#2.슬라이싱
array1=np.arange(1,10)
print(array1[0:3]) # 단일 추출을 제외한 나머지 인덱싱은 모두 데이터타입이 ndarray임
print(array1[:3])
print(array1[3:])

array1d=np.arange(1,10)
array2d=array1d.reshape(3,3)
print(array2d[0:2,0:2]) # 2차원이니까 0~1행까지 , 0열~1열까지
print(array2d[1:3,0:3]) # 1행~2행 , 0열~2열까지
print(array2d[1:3,:])
print(array2d[:2,1:]) # 0~1행 , 1~2열
print(array2d[:2,0])
# 2차원 or n차원 ndarray에서 뒤에오는 인덱스를 지우면  n-1차원 ndarray를 반환
print(array2d[0]) # axis=0 row방향값 전부를 보여줌 array2d[0,:] 동일


#3.팬시 인덱싱 : 일정한 인덱싱 집합을 리스트또는 ndarray로 지정해 해당위치에 있는 데이터의 ndarray를 반환
array3= array2d[[0,1],2] # array2d[0,2], array2d[1,2]
print('팬시',array2d,array3.tolist()) 

array4=array2d[[0,1],0:2]
print('팬시2',array2d,array4.tolist())

#4. 불린 인덱싱 : 특정 조건에 해당하는지 여부인 true/false값을 기반으로 true에 해당하는 인덱스에 있는 위치 데이터의 ndarray를 반환

array1d=np.arange(1,10)
array3=array1d[array1d>5]
print('불린',array3)
print(array1d>5)

불린_인덱스=np.array([False,False,False,False,False,True,True,True,True])
print(array1d[불린_인덱스])
a='False False False False False  True  True  True  True'
mask = np.array([x == 'True' for x in a.split()])
print(array1d[mask])

[1 2 3 4 5 6 7 8 9] 3 9 8
[ 1  2 15  4  5  6  7  8  9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
1 9 6
[1 2 3]
[1 2 3]
[4 5 6 7 8 9]
[[1 2]
 [4 5]]
[[4 5 6]
 [7 8 9]]
[[4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]
[1 4]
[1 2 3]
팬시 [[1 2 3]
 [4 5 6]
 [7 8 9]] [3, 6]
팬시2 [[1 2 3]
 [4 5 6]
 [7 8 9]] [[1, 2], [4, 5]]
불린 [6 7 8 9]
[False False False False False  True  True  True  True]
[6 7 8 9]
[6 7 8 9]


In [8]:
# 행렬의 정렬 sort()와 argsort()
# np.sort : 원행렬을 유지한체 정렬된행렬을 반환 , ndarray.sort() : 원행렬 자체를 정렬 변환 

org_array =np.array([3,1,9,5])
sort_array1=np.sort(org_array)
print(sort_array1)

sort_array2 =org_array.sort()
print('반환행렬', sort_array2) 
print('원본행렬',org_array)

# 내림차순 정렬
sort_array1_desc=np.sort(org_array)[::-1]
print(sort_array1_desc)

# axis=0은 행방향향 아래 0행부터~n행순서 아래화살표 , axis=1은 칼럼방향 오른쪽  오른쪽 화살표 

array2d=np.array([[8,12],[7,1]])

sort_array2d_axis0=np.sort(array2d,axis=0)
sort_array2d_axis1=np.sort(array2d,axis=1)
print(array2d)
print('axis=0',sort_array2d_axis0)
print('axis=1',sort_array2d_axis1)

#정렬된 행렬의 인덱스 반환하기 : 원본 행렬이 정렬되었을때, 기존 원본 행렬의 원소에 대한 인덱스를 필요로할때는 np.argsort()를 사용함
org_array=np.array([3,1,8,5])
sort_인덱스=np.argsort(org_array)
print(sort_인덱스)

[1 3 5 9]
반환행렬 None
원본행렬 [1 3 5 9]
[9 5 3 1]
[[ 8 12]
 [ 7  1]]
axis=0 [[ 7  1]
 [ 8 12]]
axis=1 [[ 8 12]
 [ 1  7]]
[1 0 3 2]


In [122]:
# argsort의 활용방법 
# 학생이름, 학생 점수라는 두개의 배열이 존재할때, 학생 점수 순으로 학생이름을 불러낼려면?
score_array=np.array([10,5,2,7,11])
name_array=np.array(['김','이','박','최','상'])

score_array_index=np.argsort(score_array)
print(score_array_index)
name_array[score_array_index]

[2 1 3 0 4]


array(['박', '이', '최', '김', '상'], dtype='<U1')

In [124]:
# 선형대수 계산 : 행렬 내적 (행렬 곱)

A=np.array([ [1,2,3],[4,5,7]])
b=np.array([[7,8],[9,10],[11,12]])

dot_product=np.dot(A,b)
print(dot_product)

[[ 58  64]
 [150 166]]


In [127]:
# 전치 transpose

a=np.array([[1,2],[3,4]])
print(a)
print(np.transpose(a))

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


# pandas

In [9]:
import pandas as pd

In [11]:
titanic_df=pd.read_csv("C:/Users/gomin/OneDrive/바탕 화면/파이썬머신러닝완벽가이드/titanic_train.csv.csv")
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S


In [13]:
print('타이타닉 행렬',titanic_df.shape)

타이타닉 행렬 (891, 12)


In [14]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [15]:
titanic_df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200


In [18]:
value_counts=titanic_df['Pclass'].value_counts()
print(value_counts)
# 인덱스값이 1,2,3이고 각각의 데이터 값이 있음

Pclass
3    491
1    216
2    184
Name: count, dtype: int64


In [19]:
titanic_df.Pclass.head()

0    3
1    1
2    3
3    1
4    3
Name: Pclass, dtype: int64

In [20]:
print(titanic_df['Embarked'].value_counts())
print(titanic_df['Embarked'].value_counts(dropna=False))

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64
Embarked
S      644
C      168
Q       77
NaN      2
Name: count, dtype: int64


In [22]:
# 넘파이 ndarray,리스트,딕셔너리를 dataframe으로 바꾸기

col_name=['col1']
list1=[1,2,3]
array=np.array(list1)

#리스트로 데이터프레임만들기
df_list1=pd.DataFrame(list1,columns=col_name)
print('1차원리스트로 만든 데이터 프레임',df_list1)

#넘파이 ndarray로 데이터프레임만들기
df_list2=pd.DataFrame(array,columns=col_name)
print('넘파이배열로 만든 데이터 프레임',df_list2)




1차원리스트로 만든 데이터 프레임    col1
0     1
1     2
2     3
넘파이배열로 만든 데이터 프레임    col1
0     1
1     2
2     3


In [34]:
#2차원 데이터프레임

col_name2=['col1','col2','col3']

list2=[[1,2,3],[11,12,13]]
array2=np.array(list2)

df_list2=pd.DataFrame(list2,columns=col_name2)
print('2차원리스트로 만든 데이터 프레임:\n',df_list2)

df_array2=pd.DataFrame(array2,columns=col_name2)
print('2차원ndaray로 만든 데이터 프레임:\n',df_array2)

2차원리스트로 만든 데이터 프레임:
    col1  col2  col3
0     1     2     3
1    11    12    13
2차원ndaray로 만든 데이터 프레임:
    col1  col2  col3
0     1     2     3
1    11    12    13


In [36]:
# 사전으로 만든 데이터 프레임

dict={'col1':[1,1],'col2':[2,12],'col3':[3,13]}
df_dict=pd.DataFrame(dict)
print(df_dict)

   col1  col2  col3
0     1     2     3
1     1    12    13


In [46]:

print(df_dict)

# 데이터프레임을 넘파이 ndarray,리스트,딕셔너리로 변환하기
# 많은 머신러닝 패키지가 ndarray를 사용함 

array3=df_dict.values
print(type(array3),df_dict.shape,array3.shape)
print(array3)

#  데이터 프레임을 리스트로 변환
list3=df_dict.values.tolist()
print(type(list3))

# 데이터프레임을 딕셔너리로 변환
dict3=df_dict.to_dict('list')
dict3


   col1  col2  col3
0     1     2     3
1     1    12    13
<class 'numpy.ndarray'> (2, 3) (2, 3)
[[ 1  2  3]
 [ 1 12 13]]
<class 'list'>


{'col1': [1, 1], 'col2': [2, 12], 'col3': [3, 13]}

In [50]:
titanic_df['Age_0']=0
titanic_df['Age_by_10']=titanic_df['Age']*10
titanic_df['Famailly_No']=titanic_df['SibSp']+titanic_df['Parch']+1
print(titanic_df.head(3))

titanic_df['Age_by_10']=titanic_df['Age_by_10']+100
titanic_df.head(3)


   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  Age_by_10  \
0      0         A/5 21171   7.2500   NaN        S      0      220.0   
1      0          PC 17599  71.2833   C85        C      0      380.0   
2      0  STON/O2. 3101282   7.9250   NaN        S      0      260.0   

   Famailly_No  
0            2  
1            2  
2            1  


,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0,Age_by_10,Famailly_No
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,320.0,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0,480.0,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,360.0,1


In [61]:
# 데이터프레임 값 삭제
# DataFrame.drop(labels =[칼럼들] , axis= 0(헹),1(칼럼) ,inplace=True,False 원본바꿀꺼임? , columns=)

drop_result=titanic_df.drop('Age_0',axis=1)
drop_result.head(3)

KeyError: "['Age_0'] not found in axis"

In [62]:
#titanic_drop_df=titanic_df.drop(['Age_0','Age_by_10','Famailly_No'],axis=1,inplace=True)
titanic_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C


In [63]:
titanic_df.drop([0,1,2],axis=0,inplace=True)
titanic_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C


In [83]:
# index 객체
titanic_df=pd.read_csv("C:/Users/gomin/OneDrive/바탕 화면/파이썬머신러닝완벽가이드/titanic_train.csv.csv")

indexes=titanic_df.index
print(indexes)
print('인덱스 객체:', np.array(indexes))

RangeIndex(start=0, stop=891, step=1)
인덱스 객체: [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 

In [78]:
# 인덱스는 1차원 배열
# 다만 만들어진 데이터 프레임의 인덱스는 수정할수가 없다
print(indexes.values[:5])
print(indexes.shape)
print(indexes[:5].values)
print(indexes[6])


[0 1 2 3 4]
(891,)
[0 1 2 3 4]
6


In [88]:
# reset_index
# 인덱스 추가하기, 인덱스가 연속된 int숫자형이 아닌경우 다시 연속 int형을 바꿀떄 많이씀 

#titanic_reset_df=titanic_df.reset_index(inplace=True)
#titanic_reset_df

titanic_df=pd.read_csv("C:/Users/gomin/OneDrive/바탕 화면/파이썬머신러닝완벽가이드/titanic_train.csv.csv")
titanic_reset_df=titanic_df.reset_index()
titanic_reset_df.head(3)

,index,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S


In [95]:
print(titanic_df['Pclass'].value_counts()) # 인덱스가 0부터가 아님
print(type(titanic_df['Pclass'].value_counts()))
value_counts=titanic_df['Pclass'].value_counts()
print(value_counts.reset_index()) # 인덱스를 0부터 시작하도록, 시리즈 데이터가 데이터프레임형태로
print(type(value_counts.reset_index()))

Pclass
3    491
1    216
2    184
Name: count, dtype: int64
<class 'pandas.core.series.Series'>
   Pclass  count
0       3    491
1       1    216
2       2    184
<class 'pandas.core.frame.DataFrame'>


In [110]:
# 데이터 셀렉션과 필터링
# 기본적인 불리언인덱셍,슬라이싱 가능 

#데이터프레임iloc[] 위치기반 / loc[] 명칭기반

data={'name':['치','김','박','수'],'year':[2011,2022,2023,2024],'gender':['남','여','여','남']}
data_df=pd.DataFrame(data,index=['하나','둘','셋','넷'])
data_df

,name,year,gender
하나,치,2011,남
둘,김,2022,여
셋,박,2023,여
넷,수,2024,남


In [111]:
print(data_df.iloc[0,0]) # 행,열위치 기준 검색
print(data_df.iloc[0:2,0:2])
print(data_df.iloc[0:2,[0,2]])
print(data_df.iloc[:,:-1])

치
   name  year
하나    치  2011
둘     김  2022
   name gender
하나    치      남
둘     김      여
   name  year
하나    치  2011
둘     김  2022
셋     박  2023
넷     수  2024


In [117]:
# data loc [] 명칭기반

print(data_df.loc['하나','name'])
print(data_df.loc['하나':'셋','name'])
print(data_df.loc[data_df.year>2011]) # iloc과 다르게 불리언인덱싱 가능

치
하나    치
둘     김
셋     박
Name: name, dtype: object
  name  year gender
둘    김  2022      여
셋    박  2023      여
넷    수  2024      남


In [119]:
#불리언 인덱싱

titanic_df.loc[titanic_df['Age']>=60,['Name','Age']].head(3)

,Name,Age
33,"Wheadon, Mr. Edward H",66.0
54,"Ostby, Mr. Engelhart Cornelius",65.0
96,"Goldschmidt, Mr. George B",71.0


In [121]:
# 정렬,aggregation,group by

titanic_sorted=titanic_df.sort_values(by=['Name'])
titanic_sorted.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
845,846,0,3,"Abbing, Mr. Anthony",male,42.0,0,0,C.A. 5547,7.55,NaN,S
746,747,0,3,"Abbott, Mr. Rossmore Edward",male,16.0,1,1,C.A. 2673,20.25,NaN,S
279,280,1,3,"Abbott, Mrs. Stanton (Rosa Hunt)",female,35.0,1,1,C.A. 2673,20.25,NaN,S


In [125]:
titanic_sorted=titanic_df.sort_values(by=['Pclass','Name'],ascending=False)
titanic_sorted.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5,NaN,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5,NaN,S
282,283,0,3,"de Pelsmaeker, Mr. Alfons",male,16.0,0,0,345778,9.5,NaN,S


In [128]:
#titanic_df[['Age','Fare']].mean()
#group by 

titanic_df.groupby(by='Pclass').count()

,PassengerId,Survived,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Pclass,,,,,,,,,,,
1,216,216,216,216,186,216,216,216,216,176,214
2,184,184,184,184,173,184,184,184,184,16,184
3,491,491,491,491,355,491,491,491,491,12,491


In [129]:
titanic_df.groupby('Pclass')['Age'].agg([max,min])

C:\Users\gomin\AppData\Local\Temp\ipykernel_18740\414103430.py:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  titanic_df.groupby('Pclass')['Age'].agg([max,min])
C:\Users\gomin\AppData\Local\Temp\ipykernel_18740\414103430.py:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  titanic_df.groupby('Pclass')['Age'].agg([max,min])


,max,min
Pclass,,
1,80.0,0.92
2,70.0,0.67
3,74.0,0.42


In [131]:
agg_format={'Age':'max','SibSp':'sum','Fare':'mean'}
titanic_df.groupby('Pclass').agg(agg_format)


,Age,SibSp,Fare
Pclass,,,
1,80.0,90,84.154687
2,70.0,74,20.662183
3,74.0,302,13.675550


In [133]:
titanic_df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [136]:
titanic_df['Cabin']=titanic_df['Cabin'].fillna('C000')
titanic_df['Cabin']
titanic_df['Age']=titanic_df['Age'].fillna(titanic_df['Age'].mean())
titanic_df['Embarked']=titanic_df['Embarked'].fillna('S')
titanic_df.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

# apply lambda 데이터 가공

In [138]:
# 함수 선언과 함수 내의 처리를 한줄 식으로 쉽게 변환하는 식임
def get_square(a):
    return a**2

In [139]:
lambda_square=lambda x:x**2
print(lambda_square(3))

9


In [140]:
#설명

* lambda x : x**2 에서 입력인자와 계산식을 :를 통해 분리함  :의 왼쪽이 입력값 , 오른쪽이 입력 식

* 입력값으로 여러개의 값을 쓸때는 map()함수를 결합한다

a=[1,2,3]
square=map(lambda x : x**2,a)

SyntaxError: invalid syntax (1196850464.py, line 3)

In [142]:
a=[1,2,3]
square=map(lambda x : x**2,a)
list(square)

[1, 4, 9]

In [143]:
# apply,lambda를 이용해서 데이터프레임에 식을 적용하기 apply가 시리즈

titanic_df['Name_len']=titanic_df['Name'].apply(lambda x : len(x))
titanic_df[['Name','Name_len']].head(3)

,Name,Name_len
0,"Braund, Mr. Owen Harris",23
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",51
2,"Heikkinen, Miss. Laina",22


In [144]:
#  if문 추가 
titanic_df['Child_Adult']=titanic_df['Age'].apply(lambda x : 'Child' if x<=15 else 'Adult') 
# <여기서 반환값 child가 먼저나오는이유는 lambda에서 :오른쪾이 반환값이기 떄문, else if 지원안함
titanic_df[['Age','Child_Adult']].head(3)

,Age,Child_Adult
0,22.0,Adult
1,38.0,Adult
2,26.0,Adult


In [147]:
titanic_df['Age_cat']=titanic_df['Age'].apply(lambda x : 'Child' if x<=15 else('Adult' if x<=60 else 'Elderly'))
titanic_df['Age_cat'].value_counts()

Age_cat
Adult      786
Child       83
Elderly     22
Name: count, dtype: int64

In [ ]:
# apply 람다 입력식에 함수를 넣기

def get_category(age):
    cat = ''
    if age<=5: cat ='Baby'
    elif age<=12: cat ='Child'
    else : cat ='Elderly'


    return 